name: Run Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]  # List the Python versions you want to test

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies using pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .  # Installs the package and dependencies defined in pyproject.toml

      # Step 4: Run tests
      - name: Run tests
        run: |
          python -m unittest discover -s tests -p "test_all.py"